### ISSUE TITLE
DB Upgrade fails with type error

### ISSUE THREAD

**Issue by bahrmichael** [Kyria/LazyBlacksmith#108]
Heya,

I'm using the docker image with a compose setup. Worked well with 1.0.4 and I did the last database I think like 10 months back. I have the skip upgrade flag set to 1, because otherwise I'm getting a different error that doesn't let me start up.

Folks reported that since the Siege Green update, blueprint numbers were not accurate anymore.

Ran the upgrade command and received the following error:

```bash
$ docker exec -u 0 -it lb-app-backend bash -c "source /venv/bin/activate && python manage.py sde_import -d"
Downloading file ... [SUCCESS]
Decompressing file ... [SUCCESS]
Starting SDE Import...

DELETE ALL TABLES
=================
Deleting rows from activity_skill
Deleting rows from activity_product
Deleting rows from activity_material
Deleting rows from activity
Deleting rows from decryptor
Deleting rows from ore_refining

IMPORT ALL TABLES
=================
=> item: 22332/22332 (10.74s) [Cannot remove items: [12194, 12180, 12181, 12182, 12183, 12184, 12185, 12186, 12187, 12188, 12190, 12191, 12192, 12193, 12195, 18037, 18039, 18041, 18043, 18045, 18047, 18049, 18051, 18053, 18057, 18059, 18061, 18063, 18065, 18067, 18591, 18593, 18599, 18603, 18605, 18607, 18611, 18613, 18615, 18617, 18619, 18625, 18597, 18595, 56631, 56632, 56633]]
=> orerefining: Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    manager.run()
  File "/venv/lib/python3.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/venv/lib/python3.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/venv/lib/python3.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/lb/lbcmd/sde_import.py", line 130, in run
    importer.import_all()
  File "/lb/lbcmd/importer.py", line 98, in import_all
    self.import_table(table[0].__name__.lower())
  File "/lb/lbcmd/importer.py", line 104, in import_table
    self.time_func(table, getattr(self, "import_" + table))
  File "/lb/lbcmd/importer.py", line 84, in time_func
    added, total, comment = f()
  File "/lb/lbcmd/importer.py", line 285, in import_orerefining
    market_group_id = int(row[3])
TypeError: <lbcmd.sde_import.SdeImport object at 0x7f0e5a7b8a50>: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Unfortunately I don't know enough python to debug this myself :(

I can confirm that all containers are up and healthy:

```
$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
e92aecfa636f        nginx:1.17                     "nginx -g 'daemon of…"   16 months ago       Up 6 minutes        80/tcp, 0.0.0.0:443->443/tcp                          lb-app-front
1ee46c579d17        anakhon/lazyblacksmith:1.0.4   "docker-entrypoint.s…"   16 months ago       Up 52 seconds       9090/tcp                                              lb-celery-beat
2503bb307b86        anakhon/lazyblacksmith:1.0.4   "docker-entrypoint.s…"   16 months ago       Up 6 minutes        9090/tcp                                              lb-app-backend
e8429e2973db        anakhon/lazyblacksmith:1.0.4   "docker-entrypoint.s…"   16 months ago       Up 52 seconds       9090/tcp                                              lb-celery
8d0c75060d5e        postgres                       "docker-entrypoint.s…"   16 months ago       Up 6 minutes        5432/tcp                                              ec2-user_db_1
1a52a3b8f04b        rabbitmq:3                     "docker-entrypoint.s…"   16 months ago       Up 6 minutes        4369/tcp, 5671-5672/tcp, 15691-15692/tcp, 25672/tcp   ec2-user_rabbitmq_1
```

But I'm noticing now that the celery processes seem to restart frequently.

```
$ docker logs lb-celery
Traceback (most recent call last):
  File "/venv/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.7/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/venv/lib/python3.7/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 419, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/venv/lib/python3.7/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/venv/lib/python3.7/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/venv/lib/python3.7/site-packages/celery/bin/worker.py", line 258, in run
    **kwargs)
  File "/venv/lib/python3.7/site-packages/celery/worker/worker.py", line 99, in __init__
    self.app.loader.init_worker()
  File "/venv/lib/python3.7/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/venv/lib/python3.7/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/venv/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/venv/lib/python3.7/site-packages/vine/promises.py", line 170, in __call__
    return self.throw()
  File "/venv/lib/python3.7/site-packages/vine/promises.py", line 167, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/venv/lib/python3.7/site-packages/celery/app/base.py", line 663, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
  File "/venv/lib/python3.7/site-packages/celery/app/base.py", line 669, in _autodiscover_tasks_from_names
    packages() if callable(packages) else packages, related_name,
  File "/venv/lib/python3.7/site-packages/celery/loaders/base.py", line 224, in autodiscover_tasks
    related_name) if mod)
  File "/venv/lib/python3.7/site-packages/celery/loaders/base.py", line 249, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/venv/lib/python3.7/site-packages/celery/loaders/base.py", line 249, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/venv/lib/python3.7/site-packages/celery/loaders/base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lb/lbtasks/tasks/__init__.py", line 5, in <module>
    from .universe.indexes import task_industry_indexes
  File "/lb/lbtasks/tasks/universe/indexes.py", line 5, in <module>
    from lazyblacksmith.extension.esipy.operations import get_industry_systems
  File "/lb/lazyblacksmith/extension/esipy/operations.py", line 13, in <module>
    get_characters = esiapp.get_v4_swagger.op['get_characters_character_id']
  File "/venv/lib/python3.7/site-packages/pyswagger/utils.py", line 93, in __getitem__
    raise e
  File "/venv/lib/python3.7/site-packages/pyswagger/utils.py", line 73, in __getitem__
    return super(ScopeDict, self).__getitem__(k)
KeyError: 'get_characters_character_id'
```

**Comment by Kyria** [comment]
you need to use the latest release: 1.0.6, it's fixed in this release: 
- NoneType was the fact (for some reason) marketgroupID was null in the SDE for 2 items
- v4.get_characters_character_id was too old and required to be updated 

your docker ps show you're using 1.0.4 tag, which won't work anymore, due to the above
I don't know how you manage your docker ecosystem, but if you have compose file, make sure to update the tag

**Comment by bahrmichael** [comment]
Good catch! I'm using docker compose, and `docker-compose restart` did not pull the new image has expected. Had to do a `docker-compose down` and `docker-compose up` to let it pull in the new image.

**Comment by bahrmichael** [comment]
Import script works again, and it looks like the data is accurate again. Thank you very much!
