### ISSUE TITLE
error when populating db

### ISSUE THREAD

**Issue by frank1210** [Kyria/LazyBlacksmith#55]
after running "python manage.py db upgrade"
i get this error:
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    manager.run()
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 73, in <module>
    run_migrations_online()
  File "migrations/env.py", line 57, in run_migrations_online
    poolclass=pool.NullPool)
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 465, in engine_from_config
    return create_engine(url, **options)
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 81, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/industria/LazyBlacksmith/env/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 102, in dbapi
    return __import__('MySQLdb')
ImportError: No module named MySQLdb

seems related that i use MariaDB as database, but couldnt find a way to work it out.

**Comment by Kyria** [comment]
> ImportError: No module named MySQLdb

This is the error actually.
As written in the prerequisites : `Database connectors depending on the one you use (MySQL 5.6+,...)`
iirc, you should install "mysqlclient" with pip for this.

**Comment by frank1210** [comment]
thanks for that 👍 now i encountered another issue, i'm hosting the website with apache but i cannot find how to set the conf file

**Comment by Kyria** [comment]
You need to use either mod_wsgi or a standalone web application server, like uwsgi or gunicorn and use apache a reverse proxy (mod_proxy).

Then you use app.py / app object as entry point of the wsgi part of the app

**Comment by frank1210** [comment]
i'm a little lost there,as i'm new to all this, but correct me if i am wrong, to run either guinicorn or mod_wsgi i need a file called wsgi.py that i need to make. after that i need to place that file inside the "LazyBlacksmith/lazyblacksmith/" directory and then set the reverse proxy in the .conf file(and enable it).

i'd end up with a conf file similar to this one:


<VirtualHost *:80>
        ServerName industria.example.com

        ProxyPassMatch ^/static !
        ProxyPass / http://127.0.0.1:8000/
        ProxyPassReverse / http://127.0.0.1:8000/
        ProxyPreserveHost On

        WSGIDaemonProcess industria python-path=/home/industria/LazyBlacksmith/lazyblacksmith
        WSGIProcessGroup industria
        WSGIScriptAlias / /home/industria/LazyBlacksmith/lazyblacksmith/wsgi.py

        Alias "/static" "/home/industria/LazyBlacksmith/lazyblacksmith/static"
        <Directory "/home/industria/LazyBlacksmith/lazyblacksmith/static">
            Require all granted
        </Directory>


</VirtualHost>


am i right or i messed up ?

**Comment by Kyria** [comment]
replace `    WSGIScriptAlias / /home/industria/LazyBlacksmith/lazyblacksmith/wsgi.py`
with `    WSGIScriptAlias / /home/industria/LazyBlacksmith/app.py`

`wsgi.py` are usually the entry point of app, using the wsgi things. Actually, you can name it however you want, as long as it does what it needs to do :)
